### ISSUE TITLE
Awaiting scripts error

### ISSUE THREAD

**Issue by Sph3x** [rhapidfyre/Cops-n-Robbers#6]
When i try join server it just write Awaiting scripts

**Comment by rhapidfyre** [comment]
You will have to send me your server's log so I can determine if it's this game mode or another resource causing it. This game mode is running fine on 3 servers, so it leads me to believe it is a different problem. However, if it's the game mode, I would like to resolve it. Please send me a link to a pastebin with your server log.

**Comment by Sph3x** [comment]
Sorry it was me missing a script realy nice work you have made keep up the good work <3
