### ISSUE TITLE
Awaiting Script's Issue witn no other Script Loading

### ISSUE THREAD

**Issue by dexstar007** [rhapidfyre/Cops-n-Robbers#9]
Hello, again there is the client Logs:
[https://pastebin.com/fQ6CgsKm](url)
And there is the server logs: 
[https://pastebin.com/fzFtFdXv](url)

My Server.cfg

> # Only change the IP if you're using a server with multiple network interfaces, otherwise change the port only.
> endpoint_add_tcp "0.0.0.0:30120"
> endpoint_add_udp "0.0.0.0:30120"
> 
> ensure spawnmanager
> ensure baseevents
> ensure chat
> ensure ghmattimysql
> ensure cnrobbers
> ensure cnr_blips
> ensure cnr_cash
> ensure cnr_charcreate
> ensure cnr_chat
> ensure cnr_clans
> ensure cnr_death
> ensure cnr_police
> ensure cnr_robberies
> ensure cnr_scoreboard
> ensure cnr_wanted
> 
> 
> 
> # This allows players to use scripthook-based plugins such as the legacy Lambda Menu.
> # Set this to 1 to allow scripthook. Do note that this does _not_ guarantee players won't be able to use external plugins.
> sv_scriptHookAllowed 0
> 
> # Uncomment this and set a password to enable RCON. Make sure to change the password - it should look like rcon_password "YOURPASSWORD"
> rcon_password "xxx"
> 
> # A comma-separated list of tags for your server.
> # For example:
> # - sets tags "drifting, cars, racing"
> # Or:
> # - sets tags "roleplay, military, tanks"
> sets tags "default"
> 
> # A valid locale identifier for your server's primary language.
> # For example "en-US", "fr-CA", "nl-NL", "de-DE", "en-GB", "pt-BR"
> sets locale "root-AQ" 
> # please DO replace root-AQ on the line ABOVE with a real language! :)
> 
> # Set an optional server info and connecting banner image url.
> # Size doesn't matter, any banner sized image will be fine.
> #sets banner_detail "https://url.to/image.png"
> #sets banner_connecting "https://url.to/image.png"
> 
> # Set your server's hostname
> sv_hostname "Testing Server"
> 
> # Nested configs!
> #exec server_internal.cfg
> 
> # Loading a server icon (96x96 PNG file)
> #load_server_icon myLogo.png
> 
> # convars which can be used in scripts
> set temp_convar "hey world!"
> 
> # Uncomment this line if you do not want your server to be listed in the server browser.
> # Do not edit it if you *do* want your server listed.
> #sv_master1 ""
> 
> # Add system admins
> add_ace group.admin command allow # allow all commands
> add_ace group.admin command.quit deny # but don't allow quit
> add_principal identifier.steam:110000100000000 group.admin # add the admin to the group
> 
> # Hide player endpoints in external log output.
> sv_endpointprivacy true
> 
> # Server player slot limit (must be between 1 and 32, unless using OneSync)
> sv_maxclients 32
> 
> # License key for your server (https://keymaster.fivem.net)
> sv_licenseKey xxxx

Hope you can find something wrong because i don't see nothing wrong

**Comment by rhapidfyre** [comment]
There are no errors or gamemode issues in the logs that I can see. Try adding mapmanager to your loadout, and ensure you have a default map loaded (such as fivem-map-hipster) and see if it loads then.

**Comment by rhapidfyre** [comment]
Be sure to report back what you find by adding mapmanager and let me know if it works or not. If it solves the issue, I'll be sure to add mapmanager as a dependency on the next push. Otherwise, if I do not hear back I'll assume this issue is resolved.

**Comment by dexstar007** [comment]
Sorry for the late answers now works fine i'm so new with fiveM forgot to add the other mode
Thanks for you awsome help.

Have a nice Day!!
